PROJECT = "ngx-discourse-2026"
DATASET = "ngx"
BUCKET  = "ngx-discourse-2026-raw"

TWEETS_RAW_STAGING = f"{DATASET}.stg_tweets_raw"
NGX_RAW_STAGING     = f"{DATASET}.stg_ngx_raw"
TWEETS_CLEAN        = f"{DATASET}.tweets_clean"
NGX_CLEAN           = f"{DATASET}.ngx_clean"
INTERVAL_SPINE      = f"{DATASET}.interval_spine"
TWEETS_RESOLVED = f"{DATASET}.tweets_resolved"
TWEET_PREMARKET_WINDOW = f"{DATASET}.tweet_premarket_window"
TWEET_INTRADAY_WINDOW  = f"{DATASET}.tweet_intraday_window"